providers = ["php"]

[variables]
IS_LARAVEL = "true"

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.tokenizer", "php83Extensions.fileinfo"]
cmds = ["curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php && mv composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer"]

[phases.build]
cmds = [
    "COMPOSER_ALLOW_SUPERUSER=1 /usr/local/bin/composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan migrate --force",
    "php artisan db:seed --class=AdminSeeder --force"
]

[start]
cmd = "php -S 0.0.0.0:$PORT server.php"
